import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex w-full h-screen flex-row">
        <div className="basis-1/2 w-1/2 h-full">
          <Image
            src="/blog.jpg"
            alt="blog"
            width={1300}
            height={956}
            className="w-full h-full object-cover"
          />
        </div>
        <div className="w-1/2 basis-1/2 h-full flex flex-col items-center justify-center">
          <div className="flex gap-2 items-center w-full justify-center">
            <Image
              src="/blogium.png"
              alt="logo"
              width={100}
              height={100}
              className="rounded-full"
            />
            <h2 className="text-3xl">Blogium</h2>
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
